### ISSUE TITLE
App Doesn't Function

### ISSUE THREAD

**Issue by ethsanders** [Tudor3510/AndroidProxom#1]
Whenever I click start, the app crashes. I have tested it on a Pixel 3 and a Moto g7, both running android 10. The fundamental proxy  code seems to be working, as someone I know made a fork for GNU Linux from this project. They just removed the android specific java code and added a CLI. (link in comment below) This shows that the problem is with the java files in the app. I logcatted this app, and the output from the crash is attatched.
`09-12 15:49:36.078 31221 31221 W System.err:    at com.tudor.android.proxom.BroadcastingThread.startThread(BroadcastingThread.java:35)
09-12 15:49:36.078 31221 31221 W System.err:    at com.tudor.android.proxom.ProxomService.onStartCommand(ProxomService.java:105)
09-12 15:49:36.079 31221 31221 E AndroidRuntime: Process: com.tudor.android.proxom, PID: 31221
09-12 15:49:36.079 31221 31221 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.tudor.android.proxom.ProxomService@5ac60f1 with Intent { cmp=com.tudor.android.proxom/.ProxomService (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.PrintStream.println(java.lang.String)' on a null object reference
09-12 15:49:36.079 31221 31221 E AndroidRuntime:        at com.tudor.android.proxom.BroadcastingThread.startThread(BroadcastingThread.java:39)
09-12 15:49:36.079 31221 31221 E AndroidRuntime:        at com.tudor.android.proxom.ProxomService.onStartCommand(ProxomService.java:105)
09-12 15:49:36.082  1395  1418 W ActivityTaskManager:   Force finishing activity com.tudor.android.proxom/.MainActivity
09-12 15:49:36.095  1395  1430 I ActivityManager: Showing crash dialog for package com.tudor.android.proxom u0
09-12 15:49:36.229  1872  1872 D InterruptionStateProvider: No heads up: unimportant notification: 0|com.tudor.android.proxom|1|null|10336
09-12 15:49:36.583  1395  1432 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{f9a0b41 u0 com.tudor.android.proxom/.MainActivity t2596 f}
09-12 15:49:36.592  1395  1432 W ActivityTaskManager: Activity pause timeout for ActivityRecord{f9a0b41 u0 com.tudor.android.proxom/.MainActivity t2596 f}
09-12 15:49:42.502  1395  1418 W ActivityTaskManager:   Force finishing activity com.tudor.android.proxom/.MainActivity
09-12 15:49:42.514  1395  4098 E InputDispatcher: Window handle Window{725d78d u0 Application Error: com.tudor.android.proxom} has no registered input channel
09-12 15:49:42.520  1395  1418 I ActivityManager: Killing 31221:com.tudor.android.proxom/u0a336 (adj 50): crash
09-12 15:49:42.558  1395  2192 D AutofillSession: handling death of Token{94ac8e6 ActivityRecord{f9a0b41 u0 com.tudor.android.proxom/.MainActivity t-1 f}} when saving=false`

The most important part of that is this:
`9-12 15:49:36.079 31221 31221 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.tudor.android.proxom.ProxomService@5ac60f1 with Intent { cmp=com.tudor.android.proxom/.ProxomService (has extras) }: java.lang.NullPointerException`

This means that the error seems to be with this file (link in comment below).

**Comment by ethsanders** [comment]
ok so the links are broken. the link to the GNU Linux version is https://github.com/CoolMineman/GNU-Linux-Proxom and the link to the broken file is https://github.com/Tudor3510/AndroidProxom/blob/master/app/src/main/java/com/tudor/android/proxom/ProxomService.java

**Comment by ethsanders** [comment]
Interestingly, the app works on bluestacks, but not on a real android phone.
